### ISSUE TITLE
PyPI v1.0.7 doesn't match GitHub tagged release

### ISSUE THREAD

**Issue by DarkAce65** [phillipdupuis/pydantic-to-typescript#12]
Hi, me again :sweat_smile:, I just updated my project to version 1.0.7 and noticed that the logging change (#6) didn't seem to make it to PyPI. The zip file on the GitHub release matches the source but the tar file seems to be some commits behind. Could the published package be updated to match the GitHub release?

**Comment by JensPfeifle** [comment]
Hello, just ran into this as well. Version 1.0.7 from PyPI includes the `eslint-disable` flag and but not the logging fix.

**Comment by DarkAce65** [comment]
Gentle bump on this @phillipdupuis if you wouldn't mind updating the published package!

**Comment by phillipdupuis** [comment]
Hi @DarkAce65 , thank you for the patience with this one 😬  I should have done it MUCH sooner.  It should be fixed now, though - I just published v1.0.8 to pypi and it includes the logging change
