### ISSUE TITLE
Any solution for the validation part of pydantic in typescript?

### ISSUE THREAD

**Issue by hugohabicht01** [phillipdupuis/pydantic-to-typescript#13]
As you know pydantic not only provides nice typehints for auto completion but also validates the data against the model and throws errors if the data does not fit into the model. Do you have any idea how that could be achieved in typescript using the interface apart from manually writing setters? My question is basically, do you know any validators in typescript that can use interface to perform the validation?

**Comment by isolationism** [comment]
Don't know how up to date this is hugo, but I'm thinking of checking out https://github.com/ForbesLindesay/typescript-json-validator to check types in runtime.

**Comment by phillipdupuis** [comment]
Hi @hugohabicht01, sorry for the very late response.

I don't know of anything validators that can use typescript interfaces directly for validation (although they may exist).

The packages I know of that *do* perform runtime validation require that you define the types as actual javascript objects, and then you can extract the typescript types via some sort of `typeof` operator.
Example: https://gcanti.github.io/io-ts/

If you already have pydantic models, I think the easiest way to do this would be to use them to generate json-schema and then use a package like ajv https://github.com/ajv-validator/ajv

**Comment by hugohabicht01** [comment]
Thanks man, I totally forgot about this issue, but in case anyone has the same issue as me, I can totally recommend using https://github.com/colinhacks/zod, a validator which both emits type definitions but also performs typechecking during the runtime
