### ISSUE TITLE
Add parameters to main function to include or exclude certain models

### ISSUE THREAD

**Issue by javierhuerta** [phillipdupuis/pydantic-to-typescript#8]
I have a pydantic model that inherits from BaseModel that has no properties but some shared configurations ...

`
class CamelModelSchema(BaseModel):

    class Config:
        alias_generator = to_camel
        allow_population_by_field_name = True
        extra = Extra.ignore

    def dict(self, ignore_alias: bool = False, by_alias: bool = True, **kwargs) -> 'DictStrAny':
            if ignore_alias:
                return super().dict(by_alias=False, **kwargs)

            return super().dict(by_alias=True, **kwargs)
`

I would like to be able to exclude it when converting from pydantic to typescript.

Thanks for this project.

**Comment by phillipdupuis** [comment]
Great point, I actually ran into this issue recently while using it for my own projects 😛  should be a relatively quick fix, I'll let you know when it's released

**Comment by phillipdupuis** [comment]
I believe this should be resolved now, I released v1.0.7 on pypi and you now have the option to exclude models by name

If you're calling it from the CLI, it should be like `pydantic2ts --module ./mymodule.py --output ./idk.ts --exclude CamelModelSchema`. Or if it's from python, it will be `generate_typescript_defs(module="./mymodule.py", output="./idk.ts", exclude=("CamelModelSchema",))`

Based on my tests this seems to work, but if you (or anyone else) find that it doesn't please let me know and we can reopen this

**Comment by javierhuerta** [comment]
Thanks!
